[mysqld]
# Puerto único para la instancia 2 
port=3307

# Rutas de directorios (Segmentación física) 
# basedir apunta a donde están tus ejecutables en C
basedir="C:/Program Files/MySQL/MySQL Server 8.4"
# datadir apunta a la nueva carpeta en D
datadir=D:/mysql_instancia2/data

# Archivos de comunicación y logs independientes
socket=D:/mysql_instancia2/mysql2.sock
log-error=D:/mysql_instancia2/data/mysql2_error.log

# Configuraciones de motor recomendadas
default-storage-engine=InnoDB
innodb_buffer_pool_size=128M